### ISSUE TITLE
"What you need to know" on the Apply page

### ISSUE THREAD

**Issue by yvonne-liu** [oliverjam/fac-site-rebuild#10]
Arguably shouldn't everything fall _under_ that section? Why are the course dates under [What you need to know](https://fac-rebuild.netlify.com/apply#what-you-need-to-know)?

**Comment by yvonne-liu** [comment]
I think I agree with this fix. Please change from "What you need to know" to "Course dates"

**Comment by oliverjam** [comment]
<img width="1792" alt="Screenshot 2020-01-22 at 17 39 19" src="https://user-images.githubusercontent.com/9408641/72918808-38e4b200-3d3e-11ea-85d3-1d1466fc7cbc.png">
