### ISSUE TITLE
Story image placeholder

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/fac-site-rebuild#13]
Stories without an accompanying image look a little weird in the carousel. Should we have a grey placeholder rectangle for those just to fill the space?

<img width="1241" alt="Screenshot 2019-11-26 at 13 30 25" src="https://user-images.githubusercontent.com/9408641/69637661-0590ea00-1051-11ea-8c02-0fdbe805a028.png">

**Comment by oliverjam** [comment]
Happy with these?
<img width="1792" alt="Screenshot 2020-01-20 at 15 28 44" src="https://user-images.githubusercontent.com/9408641/72738480-9095e880-3b99-11ea-999d-932b15b425ce.png">

**Comment by yvonne-liu** [comment]
I love it.
