### ISSUE TITLE
Apply page missing cohort image carousel

### ISSUE THREAD

**Issue by yvonne-liu** [oliverjam/fac-site-rebuild#14]
Intentional?

**Comment by oliverjam** [comment]
Basic for now. Can add arrows and shit later

<img width="1792" alt="Screenshot 2020-01-18 at 22 19 46" src="https://user-images.githubusercontent.com/9408641/72671344-ac39ab80-3a40-11ea-9a7c-f675bb992b84.png">

**Comment by yvonne-liu** [comment]
FAC10: Spring 2017
FAC13: Spring 2018 
FAC14: Summer 2018 
FACN3: Winter 2017 
FACG3: Winter 2017 (I think) 
FAC15: Winter 2018 
FAC16: Spring 2019

**Comment by oliverjam** [comment]
Should these be in ascending or descending date order? I feel like most recent cohort first makes sense
