### ISSUE TITLE
Hire page missing employer testimonials 

### ISSUE THREAD

**Issue by yvonne-liu** [oliverjam/fac-site-rebuild#15]
![Screen Shot 2019-11-26 at 7 59 30 PM](https://user-images.githubusercontent.com/22013117/69668176-473c8780-1087-11ea-82d5-e7cadd9d0395.png)

**Comment by oliverjam** [comment]
<img width="1792" alt="Screenshot 2020-01-18 at 21 54 49" src="https://user-images.githubusercontent.com/9408641/72671121-79da7f00-3a3d-11ea-8c6d-da3d6150e197.png">
