### ISSUE TITLE
Yellow vertical line only animates sometimes

### ISSUE THREAD

**Issue by yvonne-liu** [oliverjam/fac-site-rebuild#21]
I don't really know how to recreate it, but when I first click onto a page it doesn't animate, but when I click back to the same page after another page, it usually animates.

**Comment by yvonne-liu** [comment]
![Screen Shot 2020-01-20 at 8 59 16 AM](https://user-images.githubusercontent.com/22013117/72712595-4560e300-3b63-11ea-8745-2a5f038b4820.png)

**Comment by oliverjam** [comment]
lol thanks for the screenshot :P

I don't really know what could be happening there. It's just a CSS animation—are you saying when you first click on the page it's just visible and static, or it's not there at all? There's a bit of a delay on the animation so it should take a couple of seconds to animate after the page finishes loading

**Comment by yvonne-liu** [comment]
It animates sometimes, and sometimes it doesn't. There's really no pattern to it (even after the pages loads, it'll still not animate).

**Comment by oliverjam** [comment]
Hm never seen this happen. If it doesn't animate is it invisible?

**Comment by oliverjam** [comment]
problem solved: Yvonne thought it would animate whenever it scrolled into view (like the current site). This one just uses a basic CSS keyframes animation, so it animates on page load and then stays static
