### ISSUE TITLE
Staff images should link to LinkedIn profiles

### ISSUE THREAD

**Issue by yvonne-liu** [oliverjam/fac-site-rebuild#25]
Self-explanatory

**Comment by oliverjam** [comment]
Can you give me their LinkedIn URLs? Or are they on the current site?

**Comment by yvonne-liu** [comment]
https://www.linkedin.com/in/dsofer/
https://www.linkedin.com/in/iteles/
https://www.linkedin.com/in/josephsullivantanner/
https://www.linkedin.com/in/liu-yvonne/
https://www.linkedin.com/in/rebecca-radding/

**Comment by oliverjam** [comment]
Thanks
