### ISSUE TITLE
Use stripey effect for Apply sections like Stories 

### ISSUE THREAD

**Issue by yvonne-liu** [oliverjam/fac-site-rebuild#32]
Not sure that issue makes sense to anyone else but @oliverjam. 

https://github.com/oliverjam/fac-site-rebuild/issues/18

**Comment by oliverjam** [comment]
I dunno, it actually looks kinda weird

<img width="1792" alt="Screenshot 2020-01-22 at 17 46 40" src="https://user-images.githubusercontent.com/9408641/72919316-2cad2480-3d3f-11ea-8cfd-c5f93a43f802.png">

**Comment by oliverjam** [comment]
I actually prefer it without the white background, although it's a bit harder to read for such crucial info

<img width="1792" alt="Screenshot 2020-01-22 at 18 24 38" src="https://user-images.githubusercontent.com/9408641/72922183-806e3c80-3d44-11ea-9ac7-84b68f4a6b8f.png">

**Comment by oliverjam** [comment]
Maybe with a fainter stripe?

<img width="1792" alt="Screenshot 2020-01-22 at 18 26 06" src="https://user-images.githubusercontent.com/9408641/72922285-ad225400-3d44-11ea-84ec-5b43ed098b33.png">

**Comment by yvonne-liu** [comment]
I vote for fainter stripes.
