### ISSUE TITLE
Side-scroll indicator for more content

### ISSUE THREAD

**Issue by oliverjam** [oliverjam/fac-site-rebuild#48]
We're using the side-scrolling sections a fair bit. On desktop it's usually obvious that the area is scrollable because you can see part of the next item. On mobile however the items take up 100% of the width, so unless you accidentally swipe sideways you won't know there's more stuff there.

This could be a problem for e.g. the /apply steps where you really need to read them all

<img width="411" alt="Screenshot 2020-01-24 at 12 09 25" src="https://user-images.githubusercontent.com/9408641/73068215-9265f180-3ea2-11ea-989b-76c7d4cd6db8.png">

## Possible solutions

1. Put an overflow indicator like a shadow on the right when there's more stuff
1. Put left/right arrows to move to next item
1. Make items less than 100% wide (this doesn't really work for e.g. the portraits)
1. Scrap side-scrolling on mobile and just stack the items

**Comment by yvonne-liu** [comment]
4. I think

**Comment by oliverjam** [comment]
Okay I'll make all the important steps parts stack on mobile

**Comment by oliverjam** [comment]
All done. I'll leave this open so we remember to address any outstanding issues with this, but the critical info is good to go
